const countries = {
    "af-ZA": "Afrikaans (South Africa)",
    "am-ET": "Amharic (Ethiopia)",
    "ar-AE": "Arabic (United Arab Emirates)",
    "ar-AR": "Arabic (Arab World)",
    "ar-BH": "Arabic (Bahrain)",
    "ar-DZ": "Arabic (Algeria)",
    "ar-EG": "Arabic (Egypt)",
    "ar-IQ": "Arabic (Iraq)",
    "ar-JO": "Arabic (Jordan)",
    "ar-KW": "Arabic (Kuwait)",
    "ar-LB": "Arabic (Lebanon)",
    "ar-LY": "Arabic (Libya)",
    "ar-MA": "Arabic (Morocco)",
    "ar-OM": "Arabic (Oman)",
    "ar-QA": "Arabic (Qatar)",
    "ar-SA": "Arabic (Saudi Arabia)",
    "ar-SY": "Arabic (Syria)",
    "ar-TN": "Arabic (Tunisia)",
    "ar-YE": "Arabic (Yemen)",
    "az-AZ": "Azerbaijani (Azerbaijan)",
    "be-BY": "Belarusian (Belarus)",
    "bg-BG": "Bulgarian (Bulgaria)",
    "bn-BD": "Bengali (Bangladesh)",
    "bs-BA": "Bosnian (Bosnia and Herzegovina)",
    "ca-ES": "Catalan (Spain)",
    "cs-CZ": "Czech (Czech Republic)",
    "cy-GB": "Welsh (United Kingdom)",
    "da-DK": "Danish (Denmark)",
    "de-AT": "German (Austria)",
    "de-DE": "German (Germany)",
    "de-CH": "German (Switzerland)",
    "dv-MV": "Divehi (Maldives)",
    "el-GR": "Greek (Greece)",
    "en-AU": "English (Australia)",
    "en-CA": "English (Canada)",
    "en-GH": "English (Ghana)",
    "en-HK": "English (Hong Kong)",
    "en-IE": "English (Ireland)",
    "en-IN": "English (India)",
    "en-JM": "English (Jamaica)",
    "en-MT": "English (Malta)",
    "en-NZ": "English (New Zealand)",
    "en-PH": "English (Philippines)",
    "en-SG": "English (Singapore)",
    "en-GB": "English (United Kingdom)",
    "en-US": "English (United States)",
    "en-ZA": "English (South Africa)",
    "es-AR": "Spanish (Argentina)",
    "es-CL": "Spanish (Chile)",
    "es-CO": "Spanish (Colombia)",
    "es-MX": "Spanish (Mexico)",
    "es-ES": "Spanish (Spain)",
    "es-US": "Spanish (United States)",
    "et-EE": "Estonian (Estonia)",
    "fa-IR": "Persian (Iran)",
    "fi-FI": "Finnish (Finland)",
    "fr-BE": "French (Belgium)",
    "fr-CA": "French (Canada)",
    "fr-FR": "French (France)",
    "fr-CH": "French (Switzerland)",
    "ga-IE": "Irish (Ireland)",
    "gd-GB": "Scottish Gaelic (United Kingdom)",
    "gl-ES": "Galician (Spain)",
    "gu-IN": "Gujarati (India)",
    "he-IL": "Hebrew (Israel)",
    "hi-IN": "Hindi (India)",
    "hr-HR": "Croatian (Croatia)",
    "hu-HU": "Hungarian (Hungary)",
    "hy-AM": "Armenian (Armenia)",
    "id-ID": "Indonesian (Indonesia)",
    "is-IS": "Icelandic (Iceland)",
    "it-IT": "Italian (Italy)",
    "ja-JP": "Japanese (Japan)",
    "jw-ID": "Javanese (Indonesia)",
    "ka-GE": "Georgian (Georgia)",
    "kk-KZ": "Kazakh (Kazakhstan)",
    "km-KH": "Khmer (Cambodia)",
    "kn-IN": "Kannada (India)",
    "ko-KR": "Korean (South Korea)",
    "ku-IQ": "Kurdish (Iraq)",
    "ky-KG": "Kyrgyz (Kyrgyzstan)",
    "la-VN": "Latin (Vietnam)",
    "lb-LU": "Luxembourgish (Luxembourg)",
    "lo-LA": "Lao (Laos)",
    "lt-LT": "Lithuanian (Lithuania)",
    "lv-LV": "Latvian (Latvia)",
    "mg-MG": "Malagasy (Madagascar)",
    "mi-NZ": "Māori (New Zealand)",
    "mk-MK": "Macedonian (North Macedonia)",
    "ml-IN": "Malayalam (India)",
    "mn-MN": "Mongolian (Mongolia)",
    "mo-RO": "Moldovan (Romania)",
    "mr-IN": "Marathi (India)",
    "ms-MY": "Malay (Malaysia)",
    "mt-MT": "Maltese (Malta)",
    "my-MM": "Burmese (Myanmar)",
    "ne-NP": "Nepali (Nepal)",
    "nl-NL": "Dutch (Netherlands)",
    "no-NO": "Norwegian (Norway)",
    "pa-IN": "Punjabi (India)",
    "pl-PL": "Polish (Poland)",
    "pt-BR": "Portuguese (Brazil)",
    "pt-PT": "Portuguese (Portugal)",
    "ro-RO": "Romanian (Romania)",
    "ru-RU": "Russian (Russia)",
    "si-LK": "Sinhala (Sri Lanka)",
    "sk-SK": "Slovak (Slovakia)",
    "sl-SI": "Slovenian (Slovenia)",
    "sn-ZW": "Shona (Zimbabwe)",
    "so-SO": "Somali (Somalia)",
    "sq-AL": "Albanian (Albania)",
    "sr-RS": "Serbian (Serbia)",
    "sv-SE": "Swedish (Sweden)",
    "sw-KE": "Swahili (Kenya)",
    "ta-IN": "Tamil (India)",
    "te-IN": "Telugu (India)",
    "th-TH": "Thai (Thailand)",
    "tr-TR": "Turkish (Turkey)",
    "uk-UA": "Ukrainian (Ukraine)",
    "ur-PK": "Urdu (Pakistan)",
    "uz-UZ": "Uzbek (Uzbekistan)",
    "vi-VN": "Vietnamese (Vietnam)",
    "xh-ZA": "Xhosa (South Africa)",
    "yi-DE": "Yiddish (Germany)",
    "zu-ZA": "Zulu (South Africa)"
  };

  